### ISSUE TITLE
I had found error

### ISSUE THREAD

**Issue by peng1111** [lyxia/react-native-yusha-customKeyboard#1]
<RCTText/RCTTextInput.h>  file not found,I couldn't use this

**Comment by lyxia** [comment]
RN版本号是多少

**Comment by RNHaoHao** [comment]
0.46

**Comment by lyxia** [comment]
要0.50及以上版本才能用哦

**Comment by lyxia** [comment]
要0.50及以上版本才能用哦

**Comment by RNHaoHao** [comment]
我现在是0.46的。有什么办法解决吗？




------------------ 原始邮件 ------------------
发件人: "lyxia_ios"<notifications@github.com>;
发送时间: 2018年3月21日(星期三) 上午9:11
收件人: "lyxia/react-native-yusha-customKeyboard"<react-native-yusha-customKeyboard@noreply.github.com>;
抄送: "IT々じ浩Ю"<137717070@QQ.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [lyxia/react-native-yusha-customKeyboard] I had found error (#1)




要0.50及以上版本才能用哦

**Comment by RNHaoHao** [comment]
------------------ 原始邮件 ------------------
发件人: "lyxia_ios"<notifications@github.com>;
发送时间: 2018年3月21日(星期三) 上午9:11
收件人: "lyxia/react-native-yusha-customKeyboard"<react-native-yusha-customKeyboard@noreply.github.com>;
抄送: "IT々じ浩Ю"<137717070@QQ.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [lyxia/react-native-yusha-customKeyboard] I had found error (#1)




要0.50及以上版本才能用哦

**Comment by RNHaoHao** [comment]
https://github.com/lyxia/MyRNStartKit/blob/master/package.json




------------------ 原始邮件 ------------------
发件人: "lyxia_ios"<notifications@github.com>;
发送时间: 2018年3月21日(星期三) 上午9:11
收件人: "lyxia/react-native-yusha-customKeyboard"<react-native-yusha-customKeyboard@noreply.github.com>;
抄送: "IT々じ浩Ю"<137717070@QQ.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [lyxia/react-native-yusha-customKeyboard] I had found error (#1)




要0.50及以上版本才能用哦

**Comment by orzhtml** [comment]
我RN 0.43.......
