### ISSUE TITLE
ios打包时出错编译错误

### ISSUE THREAD

**Issue by simolee** [lyxia/react-native-yusha-customKeyboard#10]
在xcode中打包时出现'RCTText/RCTBaseTextInputView.h' file not found的错误。
<img width="966" alt="image" src="https://user-images.githubusercontent.com/15647735/43192241-9f678768-902f-11e8-890e-63c4728a1854.png">

**Comment by lyxia** [comment]
请给出当前RN的版本号，以及使用的react-native-yusha-customKeyboard的版本号

**Comment by simolee** [comment]
版本号如下，谢谢
"react-native": "0.55.4"
"react-native-yusha-customkeyboard": "^0.0.8",

**Comment by lyxia** [comment]
按以下两张图修改下：
![fc3690ea-af45-4683-92d1-f56b0f1bf157](https://user-images.githubusercontent.com/7269593/43254504-1bc41a18-90fa-11e8-9968-a01aa591b116.png)
![4cb8805e-5f58-40a1-a7ca-35828ebda285](https://user-images.githubusercontent.com/7269593/43254512-1e9b4ec8-90fa-11e8-9429-613b42b353af.png)

**Comment by simolee** [comment]
Hi, 看你修改了组件的源码，发现了一个小问题，就是在CutomKeyboard.m中引入漏了文件后缀.h, 不知道是不是这样，否则我这边编译通不过，感谢百忙中帮忙解决问题
![image](https://user-images.githubusercontent.com/15647735/43297309-224dcfd0-9183-11e8-8258-4505d3339ff0.png)

**Comment by lyxia** [comment]
是这样的o(╥﹏╥)o  在0.1.2中修复了
