### ISSUE TITLE
iphoneX中自定义键盘问题。

### ISSUE THREAD

**Issue by Classical1956** [lyxia/react-native-yusha-customKeyboard#2]
inputView.frame = CGRectMake(0, 0, [UIScreen mainScreen].bounds.size.width, 252);

keyBoard: {
        backgroundColor: '#f6f5f2',
        height: DeviceInfo.isIPhoneX_deprecated ? 286 : 252,
},

会导致在IphoneX中 ，自定义的点击事件没办法响应

**Comment by lyxia** [comment]
你的键盘高度不是252吗

**Comment by Classical1956** [comment]
可能我的应用场景，和你设计初衷有违背的地方。 
已经重新处理了
