### ISSUE TITLE
有适配低版本的吗？0.44.3

### ISSUE THREAD

**Issue by orzhtml** [lyxia/react-native-yusha-customKeyboard#3]

**Comment by orzhtml** [comment]
我看你写的 MyRNStartKit 是可以运行自定义键盘的，RN版本也不高，为什么这个独立出来的，需要RN0.50呢

**Comment by lyxia** [comment]
1、我用了0.50才有的属性来判断是否为iPhoneX
2、高版本的RCTTextInput和低版本的实现不一样，原生有改动
其实可以自己判断iPhoneX不用原生的，RCTTextInput弄个Tag来适配低版本的RN，只需要改iOS的原生。但是最近比较忙，有时间我会弄一个。里面其实有很多不好的地方，比如说键盘的高度也写死了，写了252，如果你有比较好的做法，或者有时间能帮我看看，欢迎你提PR ^_^

**Comment by orzhtml** [comment]
1、适当兼容低版RN是大众的
2、键盘的参数无法通过CustomTextInput去设置，不灵活，得改KeyBoards的各个js，例如键盘类型分离。
3、模拟器debug后，键盘无法弹起。
4、安卓运行不起来，是否能有更详细的配置环境描述（包括脚手架MyRNStartKit，也无法运行）。
