### ISSUE TITLE
启动时报错 Tried to register two views with the same name RNSVGPath

### ISSUE THREAD

**Issue by Sean-Snow** [lyxia/react-native-yusha-customKeyboard#8]
是不是少配置了啥。我项目本身也有SVG

系统：ios
    "react": "16.4.1",
    "react-native": "0.55.4",
    "react-native-svg": "^6.3.1",
    "react-native-yusha-customkeyboard": "^0.0.8",

**Comment by Faithnone** [comment]
遇到了相同问题 项目中有link svg 就不会报错

**Comment by aloneszjl** [comment]
我也一样

**Comment by aloneszjl** [comment]
@Sean-Snow 你项目里面的svg和这个库的svg版本不一致 冲突了，所以会报错，改成一致的就可以了

**Comment by xinghuoliaoyuan45** [comment]
me too
